### ISSUE TITLE
Simplify writing XDS.b queries

### ISSUE THREAD

**Issue by Thopap** [oehf/ipf#117]
Hello IPF Team,

I want to suggest a improvement for writing XDS.b queries.

My initial scenario was:
- get a document from the registry
- query the registry again for all documents having the same referenceId.

The problem:
- Here I was wondering that i can't use a ReferenceId (from the first document) as input for a FindDocumentsByReferenceIdQuery. I have identified that I have to use the Hl7v2Based parser:  `query.setReferenceIds(new QueryList<String>(Hl7v2Based.render(id)));`
- In addition, it is always more difficult to identify the mandatory query parameters (currently i always need to have a look at the spec).

My proposal:
- Support the ReferenceId as input of FindDocumentsByReferenceIdQuery
- Add additional constructor's to the query objects to make it easier to identify mandatory attributes in a query

I have attached a patch for FindDocumentsByReferenceIdQuery and GetDocumentsQuery:
[ipf-commons-xds.txt](https://github.com/oehf/ipf/files/349694/ipf-commons-xds.txt)

Thomas

**Comment by unixoid** [comment]
Hi Thomas,

I think that a switch to `lombok.Builder` will be a better solution.

Its advantages:
* No need to explain why the new constructor of `FindDocumentsByReferenceIdQuery` takes only three parameters out of around fifteen supported by this query type.
* No need to introduce parameters like `IdentifierType type` in the new constructor of `GetDocumentsQuery` and other similar classes.
* `lombok.Builder` has been already leveraged by Christian for constructing FHIR query objects, therefore using it in other contexts as well will increase uniformity.
* Support for using domain objects like `ReferenceId` instead of Strings as query parameter values can be added manually.

Its disadvantages:
* The whole class hierarchy of XDS queries will have to be flattened because `lombok.Builder` cannot handle properties of base classes.

@ohr, @stanojevic-boris -- your opinions?

Thank you and best regards
Dmytro

**Comment by ohr** [comment]
I've been using the @Builder internally only so far for building up some parameter objects converting from the FHIR REST request to a typed Camel Header. I'm not sure if I'm really happy with @Builder, though. And for "real" APIs I would be careful using this... one day Lombok might decide to change the structure of the generated Builder code and the API will become incompatible. And it is hard to add proper javadocs to generated builder methods.

So for now I would propose to do one or more of the following:
* keep the @Getter/@Setter style API
* add a few custom setters for the type of use cases Thomas described (e.g. allowing a List<ReferenceId> for populating a FindDocumentsByReferenceIdQuery). Shouldn't be too much effort actually
* add a static factory method that enforces initialization of mandatory parameter plus some more builder-style methods for initialization of the optional parameters
* add javax.validation annotations (like @NotNull) e.g. by depending on hibernate-validator and validating the Query at a suitable point in time

any more thoughts?

**Comment by unixoid** [comment]
I changed `QueryList<String>` to `QueryList<ReferenceId>`.  Actually the usage of `String` was an error of mine, thus this is a replacement and not an addition.

Regarding constructors: @Thopap, you may consider using Groovy with named parameters, e.g.
```
GetDocumentsQuery query = new GetDocumentsQuery(
    uuids = ['uuid1', 'uuid2'],
    uniqueIds = ['foo', 'bar'],
    ...
)
```

Regarding @NotNull and other validation stuff: we already have a pretty good XDS validation framework acting on the ebXML level.

**Comment by Thopap** [comment]
Thank for changing the ReferenceIdQuery. 
But a short question: You have removed the "String" from the FindDocumentsByReferenceIdQuery. Do you see any issue regarding the "XDSDocumentEntryReferenceIdList" support for the SQL like syntax?

**Comment by unixoid** [comment]
Please take a look again...

**Comment by Thopap** [comment]
Thank you for this improvement, which seems to be backward compatible to previous ipf releases.
