### ISSUE TITLE
Storing XDS extra metadata and querying it

### ISSUE THREAD

**Issue by shathor** [oehf/ipf#263]
I'm struggling to store XDS extra metadata and later query it.
From what I got from the documentation / discussion:
* When storing, the slot name is required to start with "urn:" (and not "urn:ihe:")
* When querying it, the slot name is required to start with "$"

See:
* https://oehf.github.io/ipf-docs/docs/ihe/xdsHandlingExtra/
* https://groups.google.com/d/msg/ipf-user/eNCx2DG0AEE/do0U9yt7IAEJ

This use case arises from the extra metadata (swiss extension):
"urn:e-health-suisse:2019:deletionStatus" ([Anhang_5_E1_V1.8.1_e PDF](https://www.e-health-suisse.ch/fileadmin/user_upload/Dokumente/2019/E/190329_Entwurf_EPDV-EDI_Anhang_5_E1_V1.8.1_e.pdf))

Could you give me a quick examples how this can be achieved?

Labels: question, swiss

**Comment by unixoid** [comment]
Take a look at https://github.com/oehf/ipf/blob/master/platform-camel/ihe/xds/src/test/groovy/org/openehealth/ipf/platform/camel/ihe/xds/iti42/TestIti42.groovy#L97 and https://github.com/oehf/ipf/blob/master/platform-camel/ihe/xds/src/test/groovy/org/openehealth/ipf/platform/camel/ihe/xds/iti42/Iti42TestRouteBuilder.groovy#L38.

Please ask your questions in the mailing list ipf-user@googlegroups.com instead of Github tickets.

Best regards
Dmytro

**Comment by shathor** [comment]
Thanks for the reply, I will pose the question in the mailing list at some later time.
