### ISSUE TITLE
jdom2 CVE vulnerability

### ISSUE THREAD

**Issue by svenhaag** [oehf/ipf#357]
The latest jdom2 v2.0.6 (from 2015!) has a CVE: https://nvd.nist.gov/vuln/detail/CVE-2021-33813

**Comment by Thopap** [comment]
Even jdom2 is a old lady, it is still widely used in many OSS projects. IPF use it for ATNA audit read + write operations. Most of the IPF transactions only emit ATNA events, where this Jdom2 issue is not relevant, since it is only applies when parsing XML. From my understanding it might be relevant when you also receive ATNA messages through through e.g. syslog. 

Looking at the Jdom2 issue (https://github.com/hunterhacker/jdom/issues/189), a update seem to be short before release.

**Comment by Thopap** [comment]
JDOM 2.0.6.1 was released containing the CVE fix. I assume spring boot dependency will reflect that as well with one of the next updated, for now IPF define the new version in its dependency management.
For documentation purpose: The commit 93f674d already contain a solution for ipf 4.1 and 4.2 without updating jdom2.
