### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by qligier** [oehf/ipf#395]
I'd like to update all dependencies when it's possible. Is that an issue for anybody (particularly for using the latest spring-boot and camel)?

I've seen a few points that need a bit of work:

org.apache.camel:camel-cxf isn't updated any more. The doc hasn't been updated, but it seems it has been split up into camel-cxf-transport, camel-cxf-soap, camel-cxf-common, etc.

There are a few dependencies that don't appear at all in the code (like ph-schematron, ph-commons, xmlsec, jakarta.jws, jakarta.jws-api, etc. Is there a reason they're still imported?

Any interested in bumping JAXB and xml-bind to v4?

**Comment by unixoid** [comment]
* `camel-cxf` is used only in tests, probably it would be easier to replace it than to adapt to its changes.
* Unused dependencies are of no use :)
* No opinion on JAXB v4.

**Comment by Thopap** [comment]
Here my remarks:

* For camel i would prefer only to use the lts releases, but a update to latest lts (3.18.x) make sense.
* for jaxb v4, i am not quiet sure. CXF 3 make use of jaxb and still use jaxb 2.3. I would recommend to wait until all major dependency use jaxb v4. 
* CXF 3.5.3 shall be used with care, since 3.5.3 has introduce a MTOM issue (not present in 3.5.2). 3.5.4 is currently in release process.
* If dependency are really not used and tests still run fine, i only see a demand if we identify some import dependency convergences between the third parties that we want to resolve in ipf. But less dependency definitions are welcome :-)
** xmlsec seems to be used in ipf at some places if i see this correctly.

Any proposal for update is welcome.
