### ISSUE TITLE
Remove deprecated code

### ISSUE THREAD

**Issue by Thopap** [oehf/ipf#456]
With the major release of IPF 5 it is a good point to remove certain code fragements that are already marked as deprecated.

**Comment by unixoid** [comment]
In the XDS classes `Status` and `AssociationType`, we still have attributes `opcode21` related to XDS.a.  Do we need them?

**Comment by ohr** [comment]
No. Xds.a is obsolete.

Christian

Dmytro Rud ***@***.***> schrieb am Do., 1. Aug. 2024, 19:46:

**Comment by unixoid** [comment]
Gentlemen,
I discovered that we still have the code `org.openehealth.ipf.commons.ihe.xds.core.metadata.AvailabilityStatus#SUBMITTED`, which does not exist in XDS since 2015 (compare ITI TF-2a section 3.18.4.1.2.3.6 in [Revision 11.0](https://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_TF_Rev11.0_Vol2a_FT_2014-09-23.pdf) vs [Revision 12.0](https://www.ihe.net/uploadedFiles/Documents/ITI/IHE_ITI_TF_Rev12.0_Vol2a_FT_2015-09-18.pdf)).  Can we delete this code or is there a reason to keep it?

**Comment by ohr** [comment]
I think you can delete it. 5.0 release will be done soon!

Christian

Dmytro Rud ***@***.***> schrieb am Mo., 27. Jan. 2025, 12:24:
