### ISSUE TITLE
Deploy artifacts to Maven Central

### ISSUE THREAD

**Issue by ohr** [oehf/ipf#67]
We should get rid on depending on self-hosted environment as its maintenance is not guaranteed.

To do so, the following has to happen:
* build on buildhive: already done, see https://buildhive.cloudbees.com/job/oehf/
* migrate documentation from confluence to github.io: see #62 
* deploy artifacts to Maven Central

There's some docs on how to achieve this, see e.g. http://central.sonatype.org/pages/requirements.html. Also it makes sense to have 

    <parent>
         <groupId>org.sonatype.oss</groupId>
         <artifactId>oss-parent</artifactId>
         <version>7</version>
    </parent>

as parent.
Furthermore we should relabel all patched/mavenized 3rd party libs under a new group ID (org.openehealth.ipf.XXX), i.e. creating Maven projects that just provide the 3rd party jars instead of building them before they are uploaded. This is o.k. as long as we retain their original license, which is mostly EPL for the OHT and EMF stuff.

**Comment by jitpack** [comment]
Btw, it's also easily available on https://jitpack.io/#oehf/ipf/ipf-3.0-m1

**Comment by stanojevic-boris** [comment]
@jitpack thanks for the hint; I'm trying it out right now and I have a problem resolving the internal dependencies inside of our project; example:
referencing:

    <dependency>
        <groupId>com.github.oehf</groupId>
        <artifactId>ipf.ipf-platform-camel-ihe-xds</artifactId>
        <version>ipf-3.0-m2</version>
    </dependency>

can not resolve the internal dependency (with other GroupID) defined in **ipf-platform-camel-core.pom**:

    <dependency>
        <groupId>org.openehealth.ipf.commons</groupId>
        <artifactId>ipf-commons-core</artifactId>
        <version>${project.version}</version>
    </dependency>

Error:

*Failed to collect dependencies at com.github.oehf:ipf.ipf-platform-camel-ihe-xds:jar:ipf-3.0-m2 -> com.github.oehf:ipf.ipf-platform-camel-ihe-ws:jar:ipf-3.0-m2 -> com.github.oehf:ipf.ipf-platform-camel-core:jar:ipf-3.0-m2 -> org.openehealth.ipf.commons:ipf-commons-core:jar:ipf-3.0-m2: Failed to read artifact descriptor for org.openehealth.ipf.commons:ipf-commons-core:jar:ipf-3.0-m2: Could not transfer artifact org.openehealth.ipf.commons:ipf-commons-core:pom:ipf-3.0-m2 from/to jitpack.io (https://jitpack.io): Failed to transfer file: https://jitpack.io/org/openehealth/ipf/commons/ipf-commons-core/ipf-3.0-m2/ipf-commons-core-ipf-3.0-m2.pom. Return code is: 400 , ReasonPhrase:Expecting: /com/github/user/repo[/module]/version/repo-version.pom. -> [Help 1]*

do we need to change the groupId's in order to make it work?
Thanks, cheers!!

**Comment by stanojevic-boris** [comment]
OK, the request at Sonatype is already resolved:
https://issues.sonatype.org/browse/OSSRH-14197
The whole "org.openehealth" space belongs to us :)
Taking the next steps...

**Comment by stanojevic-boris** [comment]
First release promoted (ipf-gazelle-1.0.3), artifacts on maven central at:
http://repo1.maven.org/maven2/org/openehealth/ipf/

**Comment by stanojevic-boris** [comment]
First IPF release promoted (ipf-3.0.0), artifacts on maven central at:
http://repo1.maven.org/maven2/org/openehealth/ipf/
Closing the Issue...

**Comment by unixoid** [comment]
Do I understand that source JARs are not available?

**Comment by unixoid** [comment]
Sorry, disregard.

**Comment by unixoid** [comment]
Sorry, it's me again.  What I actually missed were the test source jars.  I added a goal to the Maven source plugin -- will the be automatically available in the Maven repo with the next IPF release?  Moreover, the placeholder ${site.url} is not handled properly, and this leads to broken URLs like shown below:
![maven-url](https://cloud.githubusercontent.com/assets/262903/8533772/9a677c9e-2437-11e5-8503-847521c7321f.png)
Could you please take a look?

**Comment by stanojevic-boris** [comment]
Looks like this one can be considered as done; closing the issue...
