### ISSUE TITLE
Relax Validation of sourcePatientInfo

### ISSUE THREAD

**Issue by Thopap** [oehf/ipf#93]
Currently the SourcePatientInfo slot in the XDS document metadata is validated strict. E.g. a invalid birthdate format in PID-7 will fail:

`org.openehealth.ipf.commons.ihe.xds.core.validate.XDSMetaDataException: Invalid time format: 1950-10-07
        at org.openehealth.ipf.commons.ihe.xds.core.transform.hl7.DateTransformer.fromHL7(DateTransformer.java:65)
        at org.openehealth.ipf.commons.ihe.xds.core.metadata.PatientInfo.setDateOfBirth(PatientInfo.java:106)
        at org.openehealth.ipf.commons.ihe.xds.core.transform.hl7.pid.DateOfBirthPIDTransformer.fromHL7(DateOfBirthPIDTransformer.java:40)
        at org.openehealth.ipf.commons.ihe.xds.core.transform.hl7.PatientInfoTransformer.fromHL7(PatientInfoTransformer.java:66)
        at org.openehealth.ipf.commons.ihe.xds.core.transform.ebxml.DocumentEntryTransformer.addSlotsFromEbXML(DocumentEntryTransformer.java:115)
        at org.openehealth.ipf.commons.ihe.xds.core.transform.ebxml.DocumentEntryTransformer.addSlotsFromEbXML(DocumentEntryTransformer.java:1)`

Currently I have seen two projects where this was causing trouble. To have such a validation in place for incoming data is perfect, but for outgoing it might cause trouble. 

The IPF simplified datamodel try to parse the sourcePatientInfo into a java structure. Is it possible to make the conversation "lazy" (so only parse this structure if someone access it) and/or have more control if we want to have a validation or not.

**Comment by jkiddo** [comment]
Validation should always be on - leaving it off compromises the idea of proper standardization

**Comment by Thopap** [comment]
In general I agree that validation is a good citizen and I like the approach in IPF that I could decide if request and / or response validation should be applied. 

But from a xds registry perspective: If a client query for patient documents and 50 results should be returned and 1 of them contain a invalid patient birth date (e.g. some "old" data where the validation was not so strict): The current result is getting nothing instead of 50. 
- Disable the response validation has no effect on sourcePatientInfo (since the error is currently a parsing error)
- The main purpose of sourcePatientInfo is audit, is this important enough to break a whole result?

From a registry perspective i could try to reduce the impact and catch validation exceptions and try to end up with a PartialSuccess containing 49 results and 1 error. 
Also with a XDS Administrator actor support (Metadata update), it is not possible to fix the error in the Metadata, because no one can query for the document causing problems.

The perfect support from IPF looks for this example:
* For "normal" clients: I could create 50 documents with the metadata the registry currently know. The IPF response validator will detect one defect and automatically filter the result and create a PartialSuccess with 49 results and 1 error. --> Proper standardization is ensured.
* For "admin" clients: I could programmatically disable validation and provide the possibility to query and update such "defects" using Metadata Update. --> If certain situation require it, disable validation might be helpful.

**Comment by unixoid** [comment]
My **idea** was to let XDS validators use the Observer pattern -- when a validator detects an error, it shall report it (e.g. in the form of an XDSMetadataException object) to the configured observer.  The default observer would simply throw this exception, i.e. resemble the current IPF behavior.  But another type of observer could store the exception without throwing it, and additionally mark the related XDS object as "invalid", in that way providing the possibility to "recover" (and possibly revalidate) it.

**Problems** thereby:

1. Validation must be clearly separated from data transformation -- this is already done.

2. Which context information shall the observer obtain, and how?  For example, one of the fifty document entries uses wrong format for the patient birth date.  In the current implementation, when the birth date validator does not know to which patient, which document entry, and which stored query response does this birth date belong, and propagating/preserving this information over the whole call graph is a complicated task.  An alternative would be to not provide any context information, and instead to let the user traverse the whole object tree after the validation in order to discover objects marked as "invalid" -- but is this what the user does really want?

3. Which XDS metadata objects are allowed to be marked as "invalid"?  Do we need the possibility to mark as "invalid" any tiny piece of information like Code.displayName or is it optimal to consider only mid-level objects like Patient or Author?  Next, how shall detected exceptions be associated with those XDS metadata objects?  Is an interface like `Invalidable` with a method like `List<XDSMeradataException> getExceptions()` a good idea?

4. When the validators must be able to continue work after an error has been found, they must do that by working around this error -- in the simplest case, by skipping the related XDS metadata objects.  For example, when the "whole" Patient object is null, the validator shall not try to validate its birthDate attribute.  Currently, this "skipping" mechanism is not implemented, because all validators are designed to be fail-fast.  Introducing it is -- same as the context preservation described in (2) -- a major change.  

**Summary:** implementing the requested feature constitutes a large work package (a few man-months), which requires almost complete re-design of a substantial part of IPF.  
**Question**: is the supposed outcome worth the efforts?  

Suggestions, corrections, ideas, patches are as always **very** welcome.

**Comment by Thopap** [comment]
Thank you for this explanation.

I have the following suggestions to improve the current implementation:

The subclasses from the new XDSEnum:
- They requires some method renames, e.g. QueryType.getId() --> QueryType.getEbXML30(). I will now change the implementation to use the new name, but it might make sense to add the "old" methods for better backward compatiblity.
- The value "OFFICIAL_VALUES" is an array, it might be better to use that as a set, so operations like OFFICAL_VALUES.contains(...) are possible.
- For all implementations of XDSEnum, a method like "Status fromOfficialValue(String ebXML30)" or "Severity fromOfficialValue(String ebXML30)" would be helpful.

**Comment by unixoid** [comment]
Regarding the second point: Ok, I will change it, but even now the method `org.apache.commons.lang3.ArrayUtils.contains` is your friend.

Regarding the last point: does the method `fromEbXML(String ebXML)` in all enum factories (e.g. in `StatusFactory30`) not fulfill your needs?

**Comment by unixoid** [comment]
BTW, and for what to you need the method `contains()` in the second point?  When you have an `XdsEnum` value, simply take a look at its attribute `type`.  If you have an ebXML string and would like to know whether it does represent an official enum value, use `*EnumFactory.fromEbXML()`.

==> `OFFICIAL_VALUES` is a part of the internal machinery and not meant to be used by users.  Instead of changing it from an array to a set, I would now rather tend to hide it more thoroughly...

**Comment by Thopap** [comment]
Ok, i have not seen the factories, my original input was this.
Severity.valueOfOpcode30("...somestringinput...");
As I understood, this need to be changed to:
new SeverityFactory30().fromEbXML("...somestringinput...");

I will adjust my code to the new approach, maybe you could also think if it make sense here to add the static valueOfOpcode30 to the Severity class again to make upgrade life more easier.

**Comment by unixoid** [comment]
Hmm...  It seems that my patches bring more pain than benefit.  Would it not be simpler to revert them and return to the old approach (Java enums)?

**Comment by Thopap** [comment]
I have discussed this internally and I agree that it seems to be the best to rollback to the java enums. From my understanding the new appraoch does not yet address the "sourcePatientInfo" issue I was originally faced with. Maybe we need to think again on this for IPF 3.2 with focus on the issue with sourcePatientInfo.

**Comment by unixoid** [comment]
Commits reverted as discussed.

**Comment by Thopap** [comment]
The demand for this topic seems to be not too high, closing the issue as a won't fix.
